image: node:14.16.0-alpine3.11

variables:
    CI: "use"
    TAG: registry.gmdp.io/glonassmobile/mvne/project/esimpass/web

default:
  before_script:
    - mkdir -p ~/.docker/
    - cat $docker_config > ~/.docker/config.json
    - cat $npmrc > ~/.npmrc

cache:
  paths:
    - node_modules/

stages:
    - build
    - publish
    - deploy

build:
    stage: build
    script:
        - yarn
    artifacts:
        when: always
        paths:
            - build

publish_master:
    only:
        - master
    stage: publish
    image: docker:19.03.0
    dependencies:
        - build
    script:
        - cd build
        - export DOCKER_TAG=$TAG:latest
        - docker build --build-arg NPMRC="$npmrc" -t $DOCKER_TAG .
        - docker push $DOCKER_TAG

publish_release:
    only:
        - release/*
    stage: publish
    image: docker:19.03.0
    dependencies:
        - build
    script:
        - version="${CI_BUILD_REF_NAME/release\//}"    
        - cd build
        - export DOCKER_TAG=$TAG:$version
        - docker build --build-arg NPMRC="$npmrc" -t $DOCKER_TAG .
        - docker push $DOCKER_TAG

deploy_master:
    image: registry.gmdp.io/glonassmobile/devops/builder:1.7.0
    stage: deploy
    only:
        - master
    dependencies:
        - publish_master
    script:
        - export KUBECONFIG=$kube_config_cluster_yml
        - helm upgrade -i app
            --set reload=$(date -u +%Y-%m-%d_%H:%M:%S)
            --set version=latest
            --set dns=esimpass-dev.stand.gmdp.io
            -n esimpass-web-dev
            ./src/helm

deploy_release:
    image: registry.gmdp.io/glonassmobile/devops/builder:1.7.0
    stage: deploy
    only:
        - release/*
    dependencies:
        - publish_release
    script:
        - version="${CI_BUILD_REF_NAME/release\//}"    
        - export KUBECONFIG=$kube_config_cluster_yml
        - helm upgrade -i app
            --set reload=$(date -u +%Y-%m-%d_%H:%M:%S)
            --set version=$version
            --set dns=esimpass-test.stand.gmdp.io
            -n esimpass-web-test
            ./src/helm            