apiVersion: apps/v1
kind: Deployment
metadata:
    name: web
    labels:
        app: web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            terminationGracePeriodSeconds: 0
            imagePullSecrets:
              - name: regcred
            containers:
              - name: web
                image: "registry.gmdp.io/glonassmobile/mvne/project/esimpass/web:{{ .Values.version }}"
                imagePullPolicy: Always            
                env:
{{- if .Values.reload }}
                  - name: "reload"
                    value: {{ .Values.reload }}
{{- end }}
