apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: web
spec:
    tls:
      - hosts:
          - {{ .Values.dns }}
    rules:
      - host: {{ .Values.dns }}
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: 
                  number: 3000
