apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        app: web
spec:
    type: ClusterIP
    clusterIP: None
    selector:
        app: web
    ports:
      - protocol: TCP
        name: http
        port: 3000
        targetPort: 3000
